name: example
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  flutter_displaymode: ^0.6.0
  sliver_snap:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter

  dart_code_metrics: ^5.7.3
  lint: ^2.1.2


flutter:

  uses-material-design: true
