# A CI configuration to auto-publish pub packages.

name: Publish

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened, labeled, unlabeled]
  push:
    tags: ["v[0-9]+.[0-9]+.[0-9]+"]

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Publish package
      if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
      uses: dart-lang/ecosystem/.github/workflows/publish.yaml@main
      with:
        dry-run: false
      env:
        PUB_TOKEN: ${{ secrets.PUB_TOKEN }}
    permissions:
      pull-requests: write
      id-token: write
